import type { Metadata } from "next";
import { Suspense } from 'react'
import ReduxProvider from '@/redux/provider';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from './components/Nav'; // Adjust the path if needed
import { NavigationEvents } from './components/navigation-events';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[var(--color-primary)]`}
      >
        <header>
          <Nav/>
        </header>
         <ReduxProvider>
          {children}
        </ReduxProvider>
        <Suspense fallback={null}>
          <NavigationEvents />
        </Suspense>
      </body>
    </html>
  );
}